module.exports = {
    content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
    theme: {
        extend: {
            colors: {
                'accents-1': `var(--accents-1)`,
                'accents-2': `var(--accents-2)`,
                'accents-3': `var(--accents-3)`,
                'accents-4': `var(--accents-4)`,
                'accents-5': `var(--accents-5)`,
                'accents-6': `var(--accents-6)`,
                'accents-7': `var(--accents-7)`,
                'accents-8': `var(--accents-8)`,
                alert: 'var(--alert)',
                background: `var(--background)`,
                border: 'var(--border)',
                code: 'var(--code)',
                cyan: 'var(--cyan)',
                'cyan-dark': 'var(--cyanDark)',
                'cyan-light': 'var(--cyanLight)',
                'cyan-lighter': 'var(--cyanLighter)',
                error: 'var(--error)',
                'error-dark': 'var(--errorDark)',
                'error-light': 'var(--errorLight)',
                'error-lighter': 'var(--errorLighter)',
                'red-light': 'var(--redLight)',
                foreground: `var(--foreground)`,
                link: 'var(--link)',
                magenta: 'var(--magenta)',
                purple: 'var(--purpule)',
                secondary: `var(--secondary)`,
                selection: 'var(--selection)',
                success: 'var(--success)',
                'success-dark': 'var(--successDark)',
                'success-light': 'var(--successLight)',
                'success-lighter': 'var(--successLighter)',
                violet: 'var(--violet)',
                'violet-dark': 'var(--violetDark)',
                'violet-light': 'var(--violetLight)',
                'violet-lighter': 'var(--violetLighter)',
                warning: 'var(--warning)',
                'warning-dark': 'var(--warningDark)',
                'warning-light': 'var(--warningLight)',
                'warning-lighter': 'var(--warningLighter)',
            },
            height: {
                'header': `var(--header-height)`,
                'content': `var(--content-height)`,
            },
        },
    },
    plugins: [],
};